[env]
_.file = { path = ".env.json", redact = true }

PORT = "3457"
STRUS_DB_PATH = "{{ config_root }}/strus.db"
OTEL_EXPORTER_OTLP_ENDPOINT = "http://localhost:4318"
VITE_OTEL_OTLP_ENDPOINT = "/otlp"
VITE_OTEL_SERVICE_NAME = "strus-web"
