import {
  sqliteTable,
  text,
  integer,
  real,
  primaryKey,
  index,
} from "drizzle-orm/sqlite-core";
import type { AnySQLiteColumn } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

// ---------------------------------------------------------------------------
// settings
// ---------------------------------------------------------------------------

export const settings = sqliteTable("settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  // integer timestamp consistent with all other tables (was text/ISO-string)
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

// ---------------------------------------------------------------------------
// vocabLists
// ---------------------------------------------------------------------------

export const vocabLists = sqliteTable("vocab_lists", {
  id:          text("id").primaryKey(),
  name:        text("name").notNull(),
  description: text("description"),
  createdAt:   integer("created_at", { mode: "timestamp" }).notNull(),
});

// ---------------------------------------------------------------------------
// lemmas
// ---------------------------------------------------------------------------

export const lemmas = sqliteTable("lemmas", {
  id:        text("id").primaryKey(),
  /** The citation/dictionary form, e.g. "dom", "iść", "dobry" */
  lemma:     text("lemma").notNull(),
  pos:       text("pos").notNull(),
  /** How the paradigm was populated: morfeusz = auto-generated, manual = user-supplied */
  source:    text("source", { enum: ["morfeusz", "manual"] }).notNull().default("morfeusz"),
  notes:     text("notes"),
  /** Relative path to generated mnemonic image, e.g. "images/dom.png" */
  imagePath: text("image_path"),
  /** The specific image prompt generated by the text model and sent to the image model */
  imagePrompt: text("image_prompt"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

// ---------------------------------------------------------------------------
// grammarConcepts  — taxonomy tree (VoM types, reflexivity types, prefix semantics)
// ---------------------------------------------------------------------------

export const grammarConcepts = sqliteTable("grammar_concepts", {
  id:          text("id").primaryKey(),
  name:        text("name").notNull(),
  description: text("description"),
  parentId:    text("parent_id").references((): AnySQLiteColumn => grammarConcepts.id),
  createdAt:   integer("created_at", { mode: "timestamp" }).notNull(),
});

// ---------------------------------------------------------------------------
// sentences  — reusable sentence corpus
// ---------------------------------------------------------------------------

export const sentences = sqliteTable("sentences", {
  id:          text("id").primaryKey(),
  text:        text("text").notNull(),
  translation: text("translation"),
  /** 'handcrafted' | 'llm:gemini-2.0-flash-exp' | etc. */
  source:      text("source").notNull().default("handcrafted"),
  /** 1–5, nullable */
  difficulty:  integer("difficulty"),
  createdAt:   integer("created_at", { mode: "timestamp" }).notNull(),
});

// ---------------------------------------------------------------------------
// semanticClusters  — prefix families, VoM groups, aspect pairs
// ---------------------------------------------------------------------------

export const semanticClusters = sqliteTable("semantic_clusters", {
  id:          text("id").primaryKey(),
  name:        text("name").notNull(),
  /** 'prefix_family' | 'vom_group' | 'aspect_pair' */
  clusterType: text("cluster_type").notNull(),
  description: text("description"),
  createdAt:   integer("created_at", { mode: "timestamp" }).notNull(),
});

// ---------------------------------------------------------------------------
// notes
// ---------------------------------------------------------------------------

export const notes = sqliteTable("notes", {
  id:        text("id").primaryKey(),
  /** 'morph' | 'gloss' | 'basic' | 'cloze' | 'choice' | 'error' | 'classifier' */
  kind:      text("kind", { enum: ["morph", "gloss", "basic", "cloze", "choice", "error", "classifier"] }).notNull(),
  /** Populated for kind='morph' and kind='gloss'; null for kind='basic' */
  lemmaId:   text("lemma_id").references(() => lemmas.id, { onDelete: "cascade" }),
  /** For kind='gloss' and kind='basic': the prompt text shown to the user */
  front:     text("front"),
  /** For kind='gloss' and kind='basic': the answer text revealed to the user */
  back:      text("back"),
  /** Unix timestamp (seconds) — last time any card under this note was reviewed */
  lastReviewedAt: integer("last_reviewed_at"),
  /** Linked sentence for cloze/choice/error/classifier notes */
  sentenceId:     text("sentence_id").references(() => sentences.id),
  /** Grammar concept this note targets */
  conceptId:      text("concept_id").references(() => grammarConcepts.id),
  /** Semantic cluster this note belongs to */
  clusterId:      text("cluster_id").references(() => semanticClusters.id),
  /** Human-readable explanation of the grammar point */
  explanation:    text("explanation"),
  /** 'approved' | 'draft' | 'flagged' | 'rejected' */
  status:         text("status").notNull().default("approved"),
  /** JSON blob — LLM generation metadata (model, prompt, temperature, etc.) */
  generationMeta: text("generation_meta"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
}, (t) => [
  // lemmaId is queried in listsAddLemma, notesCreate, notesList, and sessionDue.
  // SQLite does NOT auto-index FK columns — explicit index required.
  index("notes_lemma_id_idx").on(t.lemmaId),
]);

// ---------------------------------------------------------------------------
// vocabListNotes  (join table)
// ---------------------------------------------------------------------------

export const vocabListNotes = sqliteTable(
  "vocab_list_notes",
  {
    listId: text("list_id")
      .notNull()
      .references(() => vocabLists.id, { onDelete: "cascade" }),
    noteId: text("note_id")
      .notNull()
      .references(() => notes.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.listId, t.noteId] })],
);

// ---------------------------------------------------------------------------
// morphForms
// ---------------------------------------------------------------------------

export const morphForms = sqliteTable("morph_forms", {
  id:        text("id").primaryKey(),
  lemmaId:   text("lemma_id")
    .notNull()
    .references(() => lemmas.id, { onDelete: "cascade" }),
  orth:      text("orth").notNull(),
  tag:       text("tag").notNull(),
  /** JSON-serialised ParsedTag */
  parsedTag: text("parsed_tag").notNull(),
  /** Relative path to generated TTS audio file, e.g. "audio/dom-subst-sg-nom-m3.mp3" */
  audioPath: text("audio_path"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
}, (t) => [
  // lemmaId is batch-fetched in sessionDue (WHERE lemmaId IN (...)) over
  // potentially large sets. SQLite does NOT auto-index FK columns.
  index("morph_forms_lemma_id_idx").on(t.lemmaId),
]);

// ---------------------------------------------------------------------------
// sentenceConcepts  — many-to-many: sentence ↔ grammar_concept
// ---------------------------------------------------------------------------

export const sentenceConcepts = sqliteTable(
  "sentence_concepts",
  {
    sentenceId: text("sentence_id").notNull().references(() => sentences.id, { onDelete: "cascade" }),
    conceptId:  text("concept_id").notNull().references(() => grammarConcepts.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.sentenceId, t.conceptId] })],
);

// ---------------------------------------------------------------------------
// semanticClusterMembers  — join table: cluster ↔ lemma
// ---------------------------------------------------------------------------

export const semanticClusterMembers = sqliteTable(
  "semantic_cluster_members",
  {
    clusterId: text("cluster_id").notNull().references(() => semanticClusters.id, { onDelete: "cascade" }),
    lemmaId:   text("lemma_id").notNull().references(() => lemmas.id, { onDelete: "cascade" }),
    /** e.g. "na+pisać: write to completion" */
    role:      text("role"),
  },
  (t) => [primaryKey({ columns: [t.clusterId, t.lemmaId] })],
);

// ---------------------------------------------------------------------------
// clozeGaps  — one row per gap; each gap generates one cloze_fill card
// ---------------------------------------------------------------------------

export const clozeGaps = sqliteTable("cloze_gaps", {
  id:             text("id").primaryKey(),
  noteId:         text("note_id").notNull().references(() => notes.id, { onDelete: "cascade" }),
  /** 1-based; matches {{1}} marker in sentence text */
  gapIndex:       integer("gap_index").notNull(),
  /** JSON array: '["chodzę","chadzam"]' */
  correctAnswers: text("correct_answers").notNull(),
  hint:           text("hint"),
  conceptId:      text("concept_id").references(() => grammarConcepts.id),
  /** 1–5, nullable */
  difficulty:     integer("difficulty"),
  explanation:    text("explanation"),
  createdAt:      integer("created_at", { mode: "timestamp" }).notNull(),
});

// ---------------------------------------------------------------------------
// choiceOptions  — one row per option per choice note
// ---------------------------------------------------------------------------

export const choiceOptions = sqliteTable("choice_options", {
  id:          text("id").primaryKey(),
  noteId:      text("note_id").notNull().references(() => notes.id, { onDelete: "cascade" }),
  optionText:  text("option_text").notNull(),
  isCorrect:   integer("is_correct", { mode: "boolean" }).notNull().default(false),
  explanation: text("explanation"),
  sortOrder:   integer("sort_order").notNull().default(0),
});

// ---------------------------------------------------------------------------
// cards
// ---------------------------------------------------------------------------

export const cards = sqliteTable(
  "cards",
  {
    id:            text("id").primaryKey(),
    noteId:        text("note_id")
      .notNull()
      .references(() => notes.id, { onDelete: "cascade" }),
    /** 'morph_form' | 'gloss_forward' | 'gloss_reverse' | 'basic_forward' | 'cloze_fill' | 'multiple_choice' | 'error_correction' | 'classify' */
    kind:          text("kind", { enum: ["morph_form", "gloss_forward", "gloss_reverse", "basic_forward", "cloze_fill", "multiple_choice", "error_correction", "classify"] }).notNull().default("morph_form"),
    /** Morphosyntactic tag — only set for kind='morph_form' */
    tag:           text("tag"),
    /** Links to cloze_gaps for kind='cloze_fill' cards */
    gapId:         text("gap_id").references(() => clozeGaps.id),
    /** CardState enum value (0=New,1=Learning,2=Review,3=Relearning) */
    state:         integer("state").notNull().default(0),
    /** Unix timestamp (seconds) */
    due:           integer("due").notNull(),
    stability:     real("stability").notNull().default(0),
    difficulty:    real("difficulty").notNull().default(0),
    elapsedDays:   integer("elapsed_days").notNull().default(0),
    scheduledDays: integer("scheduled_days").notNull().default(0),
    reps:          integer("reps").notNull().default(0),
    lapses:        integer("lapses").notNull().default(0),
    /** ts-fsrs v5: position in the learning_steps sequence (0 = start of queue) */
    learningSteps: integer("learning_steps").notNull().default(0),
    /** Unix timestamp (seconds), nullable */
    lastReview:    integer("last_review"),
  },
  (t) => [
    index("cards_due_idx").on(t.due),
    index("cards_note_id_idx").on(t.noteId),
  ],
);

// ---------------------------------------------------------------------------
// knowledgeComponents  — structural grammatical dimensions + lemma-level KCs
// ---------------------------------------------------------------------------

export const knowledgeComponents = sqliteTable(
  "knowledge_components",
  {
    id:         text("id").primaryKey(),
    /** Structural dimension or lemma-level: 'case' | 'number' | 'tense' | 'mood' | 'gender' | 'pos' | 'lemma' */
    kind:       text("kind", { enum: ["case", "number", "tense", "mood", "gender", "pos", "lemma"] }).notNull(),
    /** English label, e.g. 'genitive', 'singular', 'dom' */
    label:      text("label").notNull(),
    /** Polish label for UI, e.g. 'dopełniacz', 'liczba pojedyncza' */
    labelPl:    text("label_pl"),
    /** Glob pattern for NKJP tag matching, e.g. '*:gen:*'; null for kind='lemma' */
    tagPattern: text("tag_pattern"),
    /** FK to lemmas.id — set for kind='lemma' only, null otherwise */
    lemmaId:    text("lemma_id").references(() => lemmas.id, { onDelete: "cascade" }),
    /** CardState enum value (0=New,1=Learning,2=Review,3=Relearning) */
    state:      integer("state").notNull().default(0),
    /** Unix timestamp (seconds) */
    due:        integer("due").notNull(),
    stability:  real("stability").notNull().default(0),
    difficulty: real("difficulty").notNull().default(0),
    elapsedDays: integer("elapsed_days").notNull().default(0),
    scheduledDays: integer("scheduled_days").notNull().default(0),
    reps:       integer("reps").notNull().default(0),
    lapses:     integer("lapses").notNull().default(0),
    /** Unix timestamp (seconds), nullable */
    lastReview: integer("last_review"),
    createdAt:  integer("created_at", { mode: "timestamp" }).notNull(),
  },
  (t) => [
    index("knowledge_components_kind_idx").on(t.kind),
    index("knowledge_components_lemma_id_idx").on(t.lemmaId),
  ],
);

// ---------------------------------------------------------------------------
// cardKnowledgeComponents  — junction: card ↔ knowledge_component
// ---------------------------------------------------------------------------

export const cardKnowledgeComponents = sqliteTable(
  "card_knowledge_components",
  {
    cardId: text("card_id")
      .notNull()
      .references(() => cards.id, { onDelete: "cascade" }),
    kcId:   text("kc_id")
      .notNull()
      .references(() => knowledgeComponents.id, { onDelete: "cascade" }),
  },
  (t) => [
    primaryKey({ columns: [t.cardId, t.kcId] }),
    index("card_knowledge_components_kc_id_idx").on(t.kcId),
  ],
);

// ---------------------------------------------------------------------------
// reviews
// ---------------------------------------------------------------------------

export const reviews = sqliteTable(
  "reviews",
  {
    id:               text("id").primaryKey(),
    cardId:           text("card_id")
      .notNull()
      .references(() => cards.id, { onDelete: "cascade" }),
    /** Rating enum value (1=Again,2=Hard,3=Good,4=Easy) */
    rating:           integer("rating").notNull(),
    /** CardState before the review */
    stateBefore:      integer("state_before").notNull(),
    /** Unix timestamp — when this card was due */
    due:              integer("due").notNull(),
    /** Unix timestamp — when the review actually happened */
    reviewedAt:       integer("reviewed_at").notNull(),
    elapsedDays:      integer("elapsed_days").notNull(),
    scheduledDays:    integer("scheduled_days").notNull(),
    stabilityAfter:   real("stability_after").notNull(),
    difficultyAfter:  real("difficulty_after").notNull(),
    /** The raw answer string submitted by the learner; null if not captured */
    userAnswer:       text("user_answer"),
    /** Dynamically generated question text; null if canonical format was used */
    generatedQuestion: text("generated_question"),
    /** JSON array of morphological dimension names that were wrong, e.g. '["case","number"]'; null if correct or N/A */
    errorDimensions:  text("error_dimensions"),
  },
  (t) => [
    index("reviews_card_id_idx").on(t.cardId),
  ],
);
